# Generated by Django 5.0.4 on 2026-03-05 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField(db_index=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='OrphanedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('channel', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('failure_reason', models.CharField(max_length=500)),
                ('raw_payload', models.JSONField(default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('assigned_tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphaned_transactions', to='tenants.tenancy')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_orphans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orphaned Transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackSubaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subaccount_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('percentage_charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('paystack_response', models.JSONField(default=dict)),
                ('landlord', models.OneToOneField(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='paystack_subaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paystack Subaccount',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('paystack_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card'), ('mobile_money', 'Mobile Money (M-Pesa)'), ('bank_transfer', 'Bank Transfer')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.invoice')),
                ('tenancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tenants.tenancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.invoice')),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='tenants.tenancy')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
